// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sample.proto
#ifndef GRPC_sample_2eproto__INCLUDED
#define GRPC_sample_2eproto__INCLUDED

#include "sample.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace sample {

class SampleService final {
 public:
  static constexpr char const* service_full_name() {
    return "sample.SampleService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::sample::SampleResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::SampleResponse>> AsyncSampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::SampleResponse>>(AsyncSampleMethodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::SampleResponse>> PrepareAsyncSampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::SampleResponse>>(PrepareAsyncSampleMethodRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void SampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sample::SampleResponse>* AsyncSampleMethodRaw(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sample::SampleResponse>* PrepareAsyncSampleMethodRaw(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::sample::SampleResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>> AsyncSampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>>(AsyncSampleMethodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>> PrepareAsyncSampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>>(PrepareAsyncSampleMethodRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>* AsyncSampleMethodRaw(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>* PrepareAsyncSampleMethodRaw(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SampleMethod_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SampleMethod(::grpc::ServerContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SampleMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SampleMethod() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SampleMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SampleMethod(::grpc::ServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSampleMethod(::grpc::ServerContext* context, ::sample::SampleRequest* request, ::grpc::ServerAsyncResponseWriter< ::sample::SampleResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SampleMethod<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SampleMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SampleMethod() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::sample::SampleRequest, ::sample::SampleResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response) { return this->SampleMethod(context, request, response); }));}
    void SetMessageAllocatorFor_SampleMethod(
        ::grpc::experimental::MessageAllocator< ::sample::SampleRequest, ::sample::SampleResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sample::SampleRequest, ::sample::SampleResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SampleMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SampleMethod(::grpc::ServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SampleMethod(
      ::grpc::CallbackServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SampleMethod(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_SampleMethod<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_SampleMethod<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SampleMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SampleMethod() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SampleMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SampleMethod(::grpc::ServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SampleMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SampleMethod() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SampleMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SampleMethod(::grpc::ServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSampleMethod(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SampleMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SampleMethod() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SampleMethod(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SampleMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SampleMethod(::grpc::ServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SampleMethod(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SampleMethod(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SampleMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SampleMethod() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sample::SampleRequest, ::sample::SampleResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sample::SampleRequest, ::sample::SampleResponse>* streamer) {
                       return this->StreamedSampleMethod(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SampleMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SampleMethod(::grpc::ServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSampleMethod(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sample::SampleRequest,::sample::SampleResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SampleMethod<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SampleMethod<Service > StreamedService;
};

}  // namespace sample


#endif  // GRPC_sample_2eproto__INCLUDED
