// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sample.proto

#include "sample.pb.h"
#include "sample.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace sample {

static const char* SampleService_method_names[] = {
  "/sample.SampleService/SampleMethod",
};

std::unique_ptr< SampleService::Stub> SampleService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SampleService::Stub> stub(new SampleService::Stub(channel, options));
  return stub;
}

SampleService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SampleMethod_(SampleService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SampleService::Stub::SampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::sample::SampleResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sample::SampleRequest, ::sample::SampleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SampleMethod_, context, request, response);
}

void SampleService::Stub::experimental_async::SampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sample::SampleRequest, ::sample::SampleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SampleMethod_, context, request, response, std::move(f));
}

void SampleService::Stub::experimental_async::SampleMethod(::grpc::ClientContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SampleMethod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>* SampleService::Stub::PrepareAsyncSampleMethodRaw(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sample::SampleResponse, ::sample::SampleRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SampleMethod_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>* SampleService::Stub::AsyncSampleMethodRaw(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSampleMethodRaw(context, request, cq);
  result->StartCall();
  return result;
}

SampleService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SampleService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SampleService::Service, ::sample::SampleRequest, ::sample::SampleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SampleService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sample::SampleRequest* req,
             ::sample::SampleResponse* resp) {
               return service->SampleMethod(ctx, req, resp);
             }, this)));
}

SampleService::Service::~Service() {
}

::grpc::Status SampleService::Service::SampleMethod(::grpc::ServerContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sample

