// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/sample/v1/sample.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protos_2fsample_2fv1_2fsample_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protos_2fsample_2fv1_2fsample_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protos_2fsample_2fv1_2fsample_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protos_2fsample_2fv1_2fsample_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protos_2fsample_2fv1_2fsample_2eproto;
namespace sample {
namespace v1 {
class SampleRequest;
struct SampleRequestDefaultTypeInternal;
extern SampleRequestDefaultTypeInternal _SampleRequest_default_instance_;
class SampleResponse;
struct SampleResponseDefaultTypeInternal;
extern SampleResponseDefaultTypeInternal _SampleResponse_default_instance_;
}  // namespace v1
}  // namespace sample
PROTOBUF_NAMESPACE_OPEN
template<> ::sample::v1::SampleRequest* Arena::CreateMaybeMessage<::sample::v1::SampleRequest>(Arena*);
template<> ::sample::v1::SampleResponse* Arena::CreateMaybeMessage<::sample::v1::SampleResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sample {
namespace v1 {

// ===================================================================

class SampleRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sample.v1.SampleRequest) */ {
 public:
  inline SampleRequest() : SampleRequest(nullptr) {}
  ~SampleRequest() override;
  explicit PROTOBUF_CONSTEXPR SampleRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SampleRequest(const SampleRequest& from);
  SampleRequest(SampleRequest&& from) noexcept
    : SampleRequest() {
    *this = ::std::move(from);
  }

  inline SampleRequest& operator=(const SampleRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SampleRequest& operator=(SampleRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SampleRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SampleRequest* internal_default_instance() {
    return reinterpret_cast<const SampleRequest*>(
               &_SampleRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SampleRequest& a, SampleRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SampleRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SampleRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SampleRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SampleRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SampleRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SampleRequest& from) {
    SampleRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SampleRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sample.v1.SampleRequest";
  }
  protected:
  explicit SampleRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestSampleFieldFieldNumber = 1,
  };
  // string request_sample_field = 1 [json_name = "requestSampleField"];
  void clear_request_sample_field();
  const std::string& request_sample_field() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_request_sample_field(ArgT0&& arg0, ArgT... args);
  std::string* mutable_request_sample_field();
  PROTOBUF_NODISCARD std::string* release_request_sample_field();
  void set_allocated_request_sample_field(std::string* request_sample_field);
  private:
  const std::string& _internal_request_sample_field() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_request_sample_field(const std::string& value);
  std::string* _internal_mutable_request_sample_field();
  public:

  // @@protoc_insertion_point(class_scope:sample.v1.SampleRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_sample_field_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2fsample_2fv1_2fsample_2eproto;
};
// -------------------------------------------------------------------

class SampleResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sample.v1.SampleResponse) */ {
 public:
  inline SampleResponse() : SampleResponse(nullptr) {}
  ~SampleResponse() override;
  explicit PROTOBUF_CONSTEXPR SampleResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SampleResponse(const SampleResponse& from);
  SampleResponse(SampleResponse&& from) noexcept
    : SampleResponse() {
    *this = ::std::move(from);
  }

  inline SampleResponse& operator=(const SampleResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SampleResponse& operator=(SampleResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SampleResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SampleResponse* internal_default_instance() {
    return reinterpret_cast<const SampleResponse*>(
               &_SampleResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SampleResponse& a, SampleResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SampleResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SampleResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SampleResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SampleResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SampleResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SampleResponse& from) {
    SampleResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SampleResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sample.v1.SampleResponse";
  }
  protected:
  explicit SampleResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResponseSampleFieldFieldNumber = 1,
  };
  // string response_sample_field = 1 [json_name = "responseSampleField"];
  void clear_response_sample_field();
  const std::string& response_sample_field() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_response_sample_field(ArgT0&& arg0, ArgT... args);
  std::string* mutable_response_sample_field();
  PROTOBUF_NODISCARD std::string* release_response_sample_field();
  void set_allocated_response_sample_field(std::string* response_sample_field);
  private:
  const std::string& _internal_response_sample_field() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_response_sample_field(const std::string& value);
  std::string* _internal_mutable_response_sample_field();
  public:

  // @@protoc_insertion_point(class_scope:sample.v1.SampleResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr response_sample_field_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2fsample_2fv1_2fsample_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SampleRequest

// string request_sample_field = 1 [json_name = "requestSampleField"];
inline void SampleRequest::clear_request_sample_field() {
  _impl_.request_sample_field_.ClearToEmpty();
}
inline const std::string& SampleRequest::request_sample_field() const {
  // @@protoc_insertion_point(field_get:sample.v1.SampleRequest.request_sample_field)
  return _internal_request_sample_field();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SampleRequest::set_request_sample_field(ArgT0&& arg0, ArgT... args) {
 
 _impl_.request_sample_field_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sample.v1.SampleRequest.request_sample_field)
}
inline std::string* SampleRequest::mutable_request_sample_field() {
  std::string* _s = _internal_mutable_request_sample_field();
  // @@protoc_insertion_point(field_mutable:sample.v1.SampleRequest.request_sample_field)
  return _s;
}
inline const std::string& SampleRequest::_internal_request_sample_field() const {
  return _impl_.request_sample_field_.Get();
}
inline void SampleRequest::_internal_set_request_sample_field(const std::string& value) {
  
  _impl_.request_sample_field_.Set(value, GetArenaForAllocation());
}
inline std::string* SampleRequest::_internal_mutable_request_sample_field() {
  
  return _impl_.request_sample_field_.Mutable(GetArenaForAllocation());
}
inline std::string* SampleRequest::release_request_sample_field() {
  // @@protoc_insertion_point(field_release:sample.v1.SampleRequest.request_sample_field)
  return _impl_.request_sample_field_.Release();
}
inline void SampleRequest::set_allocated_request_sample_field(std::string* request_sample_field) {
  if (request_sample_field != nullptr) {
    
  } else {
    
  }
  _impl_.request_sample_field_.SetAllocated(request_sample_field, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.request_sample_field_.IsDefault()) {
    _impl_.request_sample_field_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sample.v1.SampleRequest.request_sample_field)
}

// -------------------------------------------------------------------

// SampleResponse

// string response_sample_field = 1 [json_name = "responseSampleField"];
inline void SampleResponse::clear_response_sample_field() {
  _impl_.response_sample_field_.ClearToEmpty();
}
inline const std::string& SampleResponse::response_sample_field() const {
  // @@protoc_insertion_point(field_get:sample.v1.SampleResponse.response_sample_field)
  return _internal_response_sample_field();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SampleResponse::set_response_sample_field(ArgT0&& arg0, ArgT... args) {
 
 _impl_.response_sample_field_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sample.v1.SampleResponse.response_sample_field)
}
inline std::string* SampleResponse::mutable_response_sample_field() {
  std::string* _s = _internal_mutable_response_sample_field();
  // @@protoc_insertion_point(field_mutable:sample.v1.SampleResponse.response_sample_field)
  return _s;
}
inline const std::string& SampleResponse::_internal_response_sample_field() const {
  return _impl_.response_sample_field_.Get();
}
inline void SampleResponse::_internal_set_response_sample_field(const std::string& value) {
  
  _impl_.response_sample_field_.Set(value, GetArenaForAllocation());
}
inline std::string* SampleResponse::_internal_mutable_response_sample_field() {
  
  return _impl_.response_sample_field_.Mutable(GetArenaForAllocation());
}
inline std::string* SampleResponse::release_response_sample_field() {
  // @@protoc_insertion_point(field_release:sample.v1.SampleResponse.response_sample_field)
  return _impl_.response_sample_field_.Release();
}
inline void SampleResponse::set_allocated_response_sample_field(std::string* response_sample_field) {
  if (response_sample_field != nullptr) {
    
  } else {
    
  }
  _impl_.response_sample_field_.SetAllocated(response_sample_field, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.response_sample_field_.IsDefault()) {
    _impl_.response_sample_field_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sample.v1.SampleResponse.response_sample_field)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace sample

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protos_2fsample_2fv1_2fsample_2eproto
