// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protos/sample/v1/sample.proto
#ifndef GRPC_protos_2fsample_2fv1_2fsample_2eproto__INCLUDED
#define GRPC_protos_2fsample_2fv1_2fsample_2eproto__INCLUDED

#include "protos/sample/v1/sample.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace sample {
namespace v1 {

class SampleService final {
 public:
  static constexpr char const* service_full_name() {
    return "sample.v1.SampleService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Sample(::grpc::ClientContext* context, const ::sample::v1::SampleRequest& request, ::sample::v1::SampleResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::v1::SampleResponse>> AsyncSample(::grpc::ClientContext* context, const ::sample::v1::SampleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::v1::SampleResponse>>(AsyncSampleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::v1::SampleResponse>> PrepareAsyncSample(::grpc::ClientContext* context, const ::sample::v1::SampleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::v1::SampleResponse>>(PrepareAsyncSampleRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Sample(::grpc::ClientContext* context, const ::sample::v1::SampleRequest* request, ::sample::v1::SampleResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Sample(::grpc::ClientContext* context, const ::sample::v1::SampleRequest* request, ::sample::v1::SampleResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sample::v1::SampleResponse>* AsyncSampleRaw(::grpc::ClientContext* context, const ::sample::v1::SampleRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sample::v1::SampleResponse>* PrepareAsyncSampleRaw(::grpc::ClientContext* context, const ::sample::v1::SampleRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Sample(::grpc::ClientContext* context, const ::sample::v1::SampleRequest& request, ::sample::v1::SampleResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::v1::SampleResponse>> AsyncSample(::grpc::ClientContext* context, const ::sample::v1::SampleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::v1::SampleResponse>>(AsyncSampleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::v1::SampleResponse>> PrepareAsyncSample(::grpc::ClientContext* context, const ::sample::v1::SampleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::v1::SampleResponse>>(PrepareAsyncSampleRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Sample(::grpc::ClientContext* context, const ::sample::v1::SampleRequest* request, ::sample::v1::SampleResponse* response, std::function<void(::grpc::Status)>) override;
      void Sample(::grpc::ClientContext* context, const ::sample::v1::SampleRequest* request, ::sample::v1::SampleResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sample::v1::SampleResponse>* AsyncSampleRaw(::grpc::ClientContext* context, const ::sample::v1::SampleRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sample::v1::SampleResponse>* PrepareAsyncSampleRaw(::grpc::ClientContext* context, const ::sample::v1::SampleRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Sample_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Sample(::grpc::ServerContext* context, const ::sample::v1::SampleRequest* request, ::sample::v1::SampleResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Sample : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Sample() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Sample() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sample(::grpc::ServerContext* /*context*/, const ::sample::v1::SampleRequest* /*request*/, ::sample::v1::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSample(::grpc::ServerContext* context, ::sample::v1::SampleRequest* request, ::grpc::ServerAsyncResponseWriter< ::sample::v1::SampleResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Sample<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Sample : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Sample() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::sample::v1::SampleRequest, ::sample::v1::SampleResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sample::v1::SampleRequest* request, ::sample::v1::SampleResponse* response) { return this->Sample(context, request, response); }));}
    void SetMessageAllocatorFor_Sample(
        ::grpc::MessageAllocator< ::sample::v1::SampleRequest, ::sample::v1::SampleResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sample::v1::SampleRequest, ::sample::v1::SampleResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Sample() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sample(::grpc::ServerContext* /*context*/, const ::sample::v1::SampleRequest* /*request*/, ::sample::v1::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Sample(
      ::grpc::CallbackServerContext* /*context*/, const ::sample::v1::SampleRequest* /*request*/, ::sample::v1::SampleResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Sample<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Sample : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Sample() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Sample() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sample(::grpc::ServerContext* /*context*/, const ::sample::v1::SampleRequest* /*request*/, ::sample::v1::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Sample : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Sample() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Sample() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sample(::grpc::ServerContext* /*context*/, const ::sample::v1::SampleRequest* /*request*/, ::sample::v1::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSample(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Sample : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Sample() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Sample(context, request, response); }));
    }
    ~WithRawCallbackMethod_Sample() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sample(::grpc::ServerContext* /*context*/, const ::sample::v1::SampleRequest* /*request*/, ::sample::v1::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Sample(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Sample : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Sample() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sample::v1::SampleRequest, ::sample::v1::SampleResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sample::v1::SampleRequest, ::sample::v1::SampleResponse>* streamer) {
                       return this->StreamedSample(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Sample() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Sample(::grpc::ServerContext* /*context*/, const ::sample::v1::SampleRequest* /*request*/, ::sample::v1::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSample(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sample::v1::SampleRequest,::sample::v1::SampleResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Sample<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Sample<Service > StreamedService;
};

}  // namespace v1
}  // namespace sample


#endif  // GRPC_protos_2fsample_2fv1_2fsample_2eproto__INCLUDED
